import os
import re
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
DOCS_DIR = ROOT_DIR / "docs"
LIBRARY_DIR = DOCS_DIR / "library"

class BlueprintCompiler:
    """
    Automated CAD and ECAD translation engine for Gundam engineering libraries.
    Generates functional OpenSCAD layouts and KiCad netlists based on parsed text traits.
    """
    def __init__(self):
        self.output_scad_dir = LIBRARY_DIR / "engineering_files" / "scad"
        self.output_kicad_dir = LIBRARY_DIR / "engineering_files" / "kicad"
        self.output_scad_dir.mkdir(parents=True, exist_ok=True)
        self.output_kicad_dir.mkdir(parents=True, exist_ok=True)

    def catalog_and_compile(self, image_name: str, extracted_text: str):
        """
        Runs regex keyword pairing to extract functional parameters and output 
        physical component layouts based on your production templates.
        """
        clean_text = extracted_text.lower()
        tags = []

        # 1. Check for Electrostatic Anti-Gravity Traits
        if "antigravity" in clean_text or "hull charge" in clean_text or "重力" in clean_text:
            tags.extend(["antigravity", "electrostatic-lift", "type-s-saiya"])
            self._generate_scad_hull(image_name)

        # 2. Check for Maxwell Particle Beam / Plasma Traits
        if "maxwell" in clean_text or "plasma" in clean_text or "beam cannon" in clean_text or "粒子" in clean_text:
            tags.extend(["maxwell-rifle", "plasma-bore", "peltier-cooling"])
            self._generate_kicad_charge_loop(image_name)

        # 3. Check for Hexadecimal / Room-Temperature Quantum Connections
        if "snap" in clean_text or "hexadecimal" in clean_text or "16-state" in clean_text:
            tags.extend(["snap-circuit", "hex-logic", "gold-lattice"])
            self._generate_hex_board_layout(image_name)

        return tags

    def _generate_scad_hull(self, name: str):
        """Generates an OpenSCAD file for a 360-segment electro-repulsive disc plate."""
        scad_code = """// Generated by Gundam News Corp AI Think Tank
// Reference: Revolutionary-Technology-Company/Antigravity
// 360-Segment Ventral Electrostatic Discharger Array

module s_saiya_ventral_segment(plate_id, angle) {
    rotate([0, 0, angle])
    translate([150, 0, 0])
    cube([50, 2, 5], center=true); // 2oz copper plate boundary surface
}

// Instantiate complete 360-degree high-voltage charging surface
difference() {
    for (i = [0 : 359]) {
        s_saiya_ventral_segment(i, i * 1);
    }
    cylinder(h=20, r=100, center=true); // Dielectric core separation boundary
}
"""
        out_path = self.output_scad_dir / f"{name}_hull.scad"
        out_path.write_text(scad_code)

    def _generate_kicad_charge_loop(self, name: str):
        """Generates a KiCad netlist path schema for high-voltage plasma excitation."""
        kicad_netlist = f"""(export (version D)
  (design
    (source "{name}_maxwell_core.sch")
    (date "{os.popen('date').read().strip()}")
    (tool "Gundam News Corp Think Tank Compiling Engine"))
  (components
    (comp (ref Q1) (value "Snap-Circuit-Qubit") (footprint "RT_Hardware:Gold_Lattice_Fracture"))
    (comp (ref U1) (value "Peltier_Bore_Chiller") (footprint "RT_Thermal:3D_Vapor_Chassis"))
    (comp (ref D1) (value "UV_Electron_Tightener") (footprint "RT_Optical:Bridgelux_LED_Array")))
  (nets
    (net (code 1) (name "GND_HULL") (node (ref Q1) (pin 1)) (node (ref U1) (pin 2)))
    (net (code 2) (name "16_STATE_BUS") (node (ref Q1) (pin 2)) (node (ref D1) (pin 1))))
)"""
        out_path = self.output_kicad_dir / f"{name}_charge_loop.net"
        out_path.write_text(kicad_netlist)

    def _generate_hex_board_layout(self, name: str):
        """Compiles a 16-state analog voltage step trace matrix based on the Univac-Aegis Bridge."""
        hex_code = """# Generated Hexadecimal 0.0V-1.0V Analog Bus Router Traces
# Employs 3oz thick copper tracing with active RTGuardRing paths
def route_hex_bus():
    voltage_steps = [x * 0.0625 for x in range(16)]
    print(f"Initializing 16-State Photonic Memory Delay Line Interface...")
    print(f"Voltage Step Resolutions Active: {voltage_steps}")
"""
        out_path = self.output_kicad_dir / f"{name}_hex_bus.py"
        out_path.write_text(hex_code)
